#!/usr/bin/env python3
"""Generates src/app/style tokens.h from style.css's @define-color lines.

The timeline is drawn in C++ (clips, playhead, waveforms), where CSS can't
reach, so its colours used to be hand-copied hex next to the CSS they
mirrored. This keeps one source: every `@define-color name #rrggbb;` in
style.css becomes `constexpr Rgb kName{...}` (and a `@define-color a @b;`
alias resolves to b's value). Run by meson at build time.
"""
import re
import sys


def main(css_path, out_path):
    colors = {}
    for match in re.finditer(r"@define-color\s+([a-z0-9_]+)\s+([^;]+);", open(css_path).read()):
        name, value = match.group(1), match.group(2).strip()
        if value.startswith("@"):
            value = colors.get(value[1:])
            if value is None:
                continue
        if re.fullmatch(r"#[0-9a-fA-F]{6}", value):
            colors[name] = value

    lines = [
        "// Generated by tools/gen_tokens.py from src/app/style/style.css. Do not edit.",
        "#pragma once",
        "",
        "namespace ustudio::app::tokens {",
        "",
        "struct Rgb",
        "{",
        "    float r, g, b;",
        "};",
        "",
    ]
    for name, value in colors.items():
        r, g, b = (int(value[i:i + 2], 16) for i in (1, 3, 5))
        camel = "".join(part.capitalize() for part in name.split("_"))
        lines.append(f"inline constexpr Rgb k{camel}{{{r / 255:.6f}f, {g / 255:.6f}f, {b / 255:.6f}f}}; // {value}")
    lines += ["", "} // namespace ustudio::app::tokens", ""]
    open(out_path, "w").write("\n".join(lines))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
