exec(open(__file__.replace('gestures.py', 'drive_base.py')).read())
click('Recover'); wait(6)
Y2, Y1 = 540, 588     # V2 clip band, V1 clip band
step('move still right', lambda: drag(130, Y2, 230, Y2))
step('undo', lambda: act('undo'))
step('trim still tail right', lambda: drag(192, Y2, 260, Y2))
step('trim still head left', lambda: drag(67, Y2, 45, Y2))
step('undo x2', lambda: act('undo', 2))
step('ctrl-drag copy still', lambda: mdrag('ctrl', 130, Y2, 300, Y2))
step('shift-drag slip still edge', lambda: mdrag('shift', 192, Y2, 170, Y2))
step('alt-drag ripple trim V1 first clip tail', lambda: mdrag('alt', 138, Y1, 120, Y1))
step('undo x3', lambda: act('undo', 3))
step('drag still down onto V1 (occupied)', lambda: drag(130, Y2, 130, Y1))
step('drag V1 clip up onto V2', lambda: drag(200, Y1, 400, Y2))
step('undo', lambda: act('undo'))
step('rubber band select V2', lambda: mdrag('shift', 400, Y2, 30 + 40, Y2 + 10))
step('ripple mode on', lambda: act('ripple-mode'))
step('ripple move still to 300', lambda: drag(130, Y2, 330, Y2))
step('ripple move V1 clip 2 to start', lambda: drag(200, Y1, 40, Y1))
step('ripple mode off', lambda: act('ripple-mode'))
step('undo x2', lambda: act('undo', 2))
step('select all + nudges', lambda: (act('select-all'), act('nudge-right', 3), act('nudge-right-10', 2), act('nudge-left', 5)))
step('tab walk', lambda: (act('active-track-down'), act('select-next-clip', 3), act('select-previous-clip', 2)))
step('markers', lambda: (act('seek-home'), act('step-forward-10', 3), act('add-marker'), act('add-marker'), act('step-forward-10'), act('add-marker'), act('remove-marker'), act('undo'), act('redo')))
step('zoom', lambda: (act('zoom-in', 6), act('zoom-out', 2), act('zoom-fit')))
step('split + ripple delete', lambda: (act('seek-home'), act('step-forward-10', 5), act('split-at-playhead'), act('select-next-clip'), act('ripple-delete-selected')))
step('play while editing', lambda: (act('play-pause'), drag(130, Y2, 180, Y2), act('undo'), act('redo'), time.sleep(2), act('play-pause')))
step('undo everything', lambda: act('undo', 30, pause=0.15))
step('redo everything', lambda: act('redo', 30, pause=0.15))
step('clear selection', lambda: act('clear-selection'))
shot('end')
if alive():
    click('Close'); wait(2); click('Discard', timeout=5)
    for _ in range(120):
        if not alive(): break
        time.sleep(0.5)
log(f"app exit code {proc.poll()}")
