exec(open(__file__.replace('mods.py', 'drive_base.py')).read())
click('Recover'); wait(6)
Y2, Y1 = 540, 588
step('ctrl-drag copy still', lambda: mdrag('ctrl', 130, Y2, 300, Y2))
step('ctrl click toggles', lambda: mdrag('ctrl', 300, Y2, 300, Y2))
step('shift-drag slip still tail', lambda: mdrag('shift', 191, Y2, 170, Y2))
step('alt-drag ripple trim V1 second clip tail', lambda: mdrag('alt', 245, Y1, 225, Y1))
step('alt-drag ripple trim still head', lambda: mdrag('alt', 67, Y2, 90, Y2))
step('shift rubber band', lambda: mdrag('shift', 600, 520, 50, 592))
step('drag group (after band)', lambda: drag(130, Y2, 200, Y2))
step('undo x6', lambda: act('undo', 6))
step('redo x6', lambda: act('redo', 6))
shot('end')
proc.terminate(); proc.wait(30)
