exec(open(__file__.replace('stale_selection.py', 'drive_base.py')).read())
click('Recover'); wait(6)
act('select-all')
click('Show or hide the media browser'); wait(3)
mouse(160, 162, 'abs'); time.sleep(0.2); mouse(160, 162, 'b3c'); wait(1, 'context menu')
shot('menu')
click('Remove from Project', timeout=5); wait(2)
shot('removed')
act('ripple-delete-selected'); wait(3)
log(f"alive after ripple delete: {alive()} rc={proc.poll()}")
shot('after')
if alive():
    act('delete-selected-clip'); wait(1); act('nudge-right'); wait(1)
    log(f"alive: {alive()}")
    proc.terminate(); proc.wait(30)
